apiVersion: v2
name: voting-app-argocd
description: ArgoCD Applications for the Voting App using App of Apps pattern
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - argocd
  - gitops
  - voting-app
  - app-of-apps
home: https://github.com/CHARANPRAJWAL/example-voting-app-argocd-k8s.git
sources:
  - https://github.com/CHARANPRAJWAL/example-voting-app-argocd-k8s.git
maintainers:
  - name: charan prajwal
    email: charanprajwal001@gmail.com