apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: result-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CHARANPRAJWAL/example-voting-app-argocd-k8s.git
    targetRevision: HEAD
    path: k8s-specifications
    directory:
      include: result.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 