# Development environment values
global:
  namespace: voting-app-dev
  repoURL: https://github.com/CHARANPRAJWAL/example-voting-app-argocd-k8s.git
  targetRevision: develop
  project: default

argocd:
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

syncPolicy:
  automated:
    prune: false  # Disable pruning in dev for safety
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true

applications:
  root:
    enabled: true
    name: voting-app-root-dev
    path: k8s-specifications/argocd-apps
  
  database:
    enabled: true
    name: database-app-dev
    path: k8s-specifications
    directory:
      include: db.yaml
  
  redis:
    enabled: true
    name: redis-app-dev
    path: k8s-specifications
    directory:
      include: redis.yaml
  
  vote:
    enabled: true
    name: vote-app-dev
    path: k8s-specifications
    directory:
      include: vote.yaml
  
  result:
    enabled: true
    name: result-app-dev
    path: k8s-specifications
    directory:
      include: result.yaml
  
  worker:
    enabled: true
    name: worker-app-dev
    path: k8s-specifications
    directory:
      include: worker.yaml 