# Default values for voting-app-argocd
# This is a YAML-formatted file.

# Global configuration
global:
  namespace: voting-app
  repoURL: https://github.com/CHARANPRAJWAL/example-voting-app-argocd-k8s.git
  targetRevision: HEAD
  project: default

# ArgoCD configuration
argocd:
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

# Sync policy configuration
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true

# Individual application configurations
applications:
  # Root application that manages all others
  root:
    enabled: true
    name: voting-app-root
    path: k8s-specifications/argocd-apps
  
  # Database application
  database:
    enabled: true
    name: database-app
    path: k8s-specifications
    directory:
      include: db.yaml
  
  # Redis application
  redis:
    enabled: true
    name: redis-app
    path: k8s-specifications
    directory:
      include: redis.yaml
  
  # Vote application
  vote:
    enabled: true
    name: vote-app
    path: k8s-specifications
    directory:
      include: vote.yaml
  
  # Result application
  result:
    enabled: true
    name: result-app
    path: k8s-specifications
    directory:
      include: result.yaml
  
  # Worker application
  worker:
    enabled: true
    name: worker-app
    path: k8s-specifications
    directory:
      include: worker.yaml 